### ISSUE TITLE
Having a tough time getting even a simple project to work using purs-nix

### ISSUE THREAD

**Issue by harryprayiv** [LovelaceAcademy/nix-templates#167]
I have been struggling with the pix output of this flake.  Even a simple hello world using halogen has confounded me.  My issues are (perhaps) related to the nodejs aspects of this flake.  

Here's a repo that should reproduce my issues as they are today: [halogenWorld](https://github.com/harryprayiv/halogenWorld).  If you have any suggestions whatsoever, please let me know.

**Comment by klarkc** [comment]
Your project is building. I believe the problem you're is trying to run the output of nix in nodejs (instead of a browser environment). To use it in a browser, you can `nix build .#bundle` or `nix build .#output`, then import the `result` or `result/Main/index.js` file in a html file and open the file in the browser.

Because this is a minimal template, it does not have such boilerplate (for running on browsers using dev servers), for that you can take inspiration on `pix-ctl-full` (which uses webpack running the dev server), or build your own with other option (like vite or parcel).

For more info on purs-nix outputs, I believe [this is the right place](https://github.com/purs-nix/purs-nix/blob/master/docs/purs-nix.md).

**Comment by klarkc** [comment]
[Here](https://github.com/LovelaceAcademy/PlutusExperience/tree/901bc9ff3399a49a353adf09f7d011b0af64ff69/modules/M11-a-vesting-contract-ii/dapp) is another example of project with webpack, halogen and purs-nix working together.

**Comment by klarkc** [comment]
@harryprayiv PR for a `pix-halogen` is welcome (:

**Comment by harryprayiv** [comment]
Thanks!  I'll take a while to digest this....but you're fast!

**Comment by klarkc** [comment]
@harryprayiv closing this, please open a new issue if something specific breaks. Tyvm.
